# Generated by Django 3.2.12 on 2022-08-09 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alamat_kelas_pendidikan_penghasilan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alamat',
        ),
        migrations.AlterModelOptions(
            name='kelas',
            options={'verbose_name_plural': 'Jenjang Kelas Pendidikan Santri'},
        ),
    ]
