# Generated by Django 3.2.12 on 2022-08-09 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20220809_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True, null=True)),
                ('nis', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_lengkap', models.CharField(blank=True, max_length=300, null=True)),
                ('nama_panggilan', models.CharField(blank=True, max_length=50, null=True)),
                ('gender_santri', models.CharField(blank=True, choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=200, null=True)),
                ('nik', models.CharField(blank=True, max_length=250, null=True)),
                ('tetala', models.CharField(blank=True, max_length=350, null=True)),
                ('anak_ke', models.IntegerField(blank=True, null=True)),
                ('saudara_kandung', models.IntegerField(blank=True, null=True)),
                ('saudara_tiri', models.IntegerField(blank=True, null=True)),
                ('saudara_angkat', models.IntegerField(blank=True, null=True)),
                ('tinggi_badan', models.IntegerField(blank=True, null=True)),
                ('berat_badan', models.IntegerField(blank=True, null=True)),
                ('golongan_darah', models.CharField(blank=True, max_length=50, null=True)),
                ('agama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.agama')),
                ('bahasa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.bahasa')),
                ('status_anak', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.status_anak')),
            ],
            options={
                'verbose_name_plural': 'Data Santri',
            },
        ),
    ]
