# Generated by Django 3.2.12 on 2022-08-09 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_pendaftaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='alamat',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='alamat_lembaga_formal',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='alamat_pondok',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='asal_pondok',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='ayah',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='ibu',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='kelas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.kelas'),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='nama_lembaga_formal',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='pekerjaan_ayah',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='pekerjaan_ibu',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='pekerjaan_wali',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='pendidikan_ayah',
            field=models.CharField(blank=True, choices=[('Tidak Sekolah', 'Tidak Sekolah'), ('Putus SD', 'Putus SD'), ('SD Sederajat', 'SD Sederajat'), ('SMP Sederajat', 'SMP Sederajat'), ('SMA Sederajat', 'SMA Sederajat'), ('Sarjana', 'Sarjana')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='pendidikan_ibu',
            field=models.CharField(blank=True, choices=[('Tidak Sekolah', 'Tidak Sekolah'), ('Putus SD', 'Putus SD'), ('SD Sederajat', 'SD Sederajat'), ('SMP Sederajat', 'SMP Sederajat'), ('SMA Sederajat', 'SMA Sederajat'), ('Sarjana', 'Sarjana')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='pendidikan_wali',
            field=models.CharField(blank=True, choices=[('Tidak Sekolah', 'Tidak Sekolah'), ('Putus SD', 'Putus SD'), ('SD Sederajat', 'SD Sederajat'), ('SMP Sederajat', 'SMP Sederajat'), ('SMA Sederajat', 'SMA Sederajat'), ('Sarjana', 'Sarjana')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='penghasilan_ayah',
            field=models.CharField(blank=True, choices=[('Kurang dari Rp. 1.000.000', 'Kurang dari Rp. 1.000.000'), ('Rp. 1.000.000 - Rp. 2.000.000', 'Rp. 1.000.000 - Rp. 2.000.000'), ('Lebih dari Rp. 2.000.000', 'Lebih dari Rp. 2.000.000')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='penghasilan_ibu',
            field=models.CharField(blank=True, choices=[('Kurang dari Rp. 1.000.000', 'Kurang dari Rp. 1.000.000'), ('Rp. 1.000.000 - Rp. 2.000.000', 'Rp. 1.000.000 - Rp. 2.000.000'), ('Lebih dari Rp. 2.000.000', 'Lebih dari Rp. 2.000.000')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='penghasilan_wali',
            field=models.CharField(blank=True, choices=[('Kurang dari Rp. 1.000.000', 'Kurang dari Rp. 1.000.000'), ('Rp. 1.000.000 - Rp. 2.000.000', 'Rp. 1.000.000 - Rp. 2.000.000'), ('Lebih dari Rp. 2.000.000', 'Lebih dari Rp. 2.000.000')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='pindah_pondok',
            field=models.CharField(blank=True, choices=[('Lulus', 'Lulus'), ('Mutasi', 'Mutasi')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='riwayat_ayah',
            field=models.CharField(blank=True, choices=[('Masih Hidup', 'Masih Hidup'), ('Meninggal Dunia', 'Meninggal Dunia')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='riwayat_ibu',
            field=models.CharField(blank=True, choices=[('Masih Hidup', 'Masih Hidup'), ('Meninggal Dunia', 'Meninggal Dunia')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='riwayat_wali',
            field=models.CharField(blank=True, choices=[('Masih Hidup', 'Masih Hidup'), ('Meninggal Dunia', 'Meninggal Dunia')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='tanggal_mondok',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='telp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='tetala_ayah',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='tetala_ibu',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='tetala_wali',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='wali',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
