# Generated by Django 3.2.12 on 2022-08-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20220809_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendaftaran',
            name='tetala',
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='tempat_kelahiran',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='tgl_lahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
