# Generated by Django 3.2.12 on 2022-08-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20220809_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendaftaran',
            name='tetala_ayah',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='tetala_ibu',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='tetala_wali',
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='tempat_kelahiran_ayah',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='tempat_kelahiran_ibu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='tempat_kelahiran_wali',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='tgl_lahir_ayah',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='tgl_lahir_ibu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='tgl_lahir_wali',
            field=models.DateField(blank=True, null=True),
        ),
    ]
