# Generated by Django 3.2.12 on 2022-08-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20220809_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
