# Generated by Django 3.2.12 on 2022-08-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_pendaftaran_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendaftaran',
            name='foto',
        ),
    ]
