# Generated by Django 3.2.12 on 2022-09-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_wilayah'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='status_santri',
            field=models.CharField(blank=True, choices=[('Aktif', 'Aktif'), ('Lulus', 'Lulus')], max_length=200, null=True),
        ),
    ]
