# Generated by Django 3.2.12 on 2022-09-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_pendaftaran_status_santri'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='tgl_berhenti',
            field=models.DateField(blank=True, null=True),
        ),
    ]
