# Generated by Django 3.2.12 on 2022-09-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_pendaftaran_tgl_berhenti'),
    ]

    operations = [
        migrations.AddField(
            model_name='wilayah',
            name='nama_kepala',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
