# Generated by Django 3.2.12 on 2022-09-16 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_wilayah_nama_kepala'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendaftaran',
            old_name='alamat_lembaga_formal',
            new_name='alamat_lembaga',
        ),
        migrations.RenameField(
            model_name='pendaftaran',
            old_name='alamat_pondok',
            new_name='alamat_sekolah',
        ),
        migrations.RenameField(
            model_name='pendaftaran',
            old_name='asal_pondok',
            new_name='asal_sekolah',
        ),
        migrations.RenameField(
            model_name='pendaftaran',
            old_name='pindah_pondok',
            new_name='keterangan_sekolah',
        ),
        migrations.RenameField(
            model_name='pendaftaran',
            old_name='nama_lembaga_formal',
            new_name='masuk_lembaga',
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='wilayah',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.wilayah'),
        ),
    ]
