# Generated by Django 3.2.12 on 2022-09-16 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_auto_20220916_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='bahasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.bahasa'),
        ),
    ]
