# Generated by Django 3.2.12 on 2022-09-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_alter_pendaftaran_bahasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
