# Generated by Django 3.2.12 on 2022-09-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0026_wilayah_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='foto',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
