# Generated by Django 3.2.12 on 2022-09-18 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0027_alter_pendaftaran_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True, null=True)),
                ('nis', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_lengkap', models.CharField(blank=True, max_length=300, null=True)),
                ('nama_panggilan', models.CharField(blank=True, max_length=50, null=True)),
                ('gender_santri', models.CharField(blank=True, choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=200, null=True)),
                ('nik', models.CharField(blank=True, max_length=250, null=True)),
                ('tempat_kelahiran', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('alamat', models.CharField(blank=True, max_length=350, null=True)),
                ('anak_ke', models.IntegerField(blank=True, null=True)),
                ('saudara_kandung', models.IntegerField(blank=True, null=True)),
                ('saudara_tiri', models.IntegerField(blank=True, null=True)),
                ('saudara_angkat', models.IntegerField(blank=True, null=True)),
                ('tinggi_badan', models.IntegerField(blank=True, null=True)),
                ('berat_badan', models.IntegerField(blank=True, null=True)),
                ('golongan_darah', models.CharField(blank=True, max_length=50, null=True)),
                ('status_santri', models.CharField(blank=True, choices=[('Aktif', 'Aktif'), ('Lulus', 'Lulus')], max_length=200, null=True)),
                ('tgl_berhenti', models.DateField(blank=True, null=True)),
                ('telp', models.CharField(blank=True, max_length=200, null=True)),
                ('asal_sekolah', models.CharField(blank=True, max_length=250, null=True)),
                ('alamat_sekolah', models.CharField(blank=True, max_length=250, null=True)),
                ('keterangan_sekolah', models.CharField(blank=True, choices=[('Lulus', 'Lulus'), ('Mutasi', 'Mutasi')], max_length=50, null=True)),
                ('tanggal_mondok', models.DateField(blank=True, null=True)),
                ('masuk_lembaga', models.CharField(blank=True, max_length=250, null=True)),
                ('alamat_lembaga', models.CharField(blank=True, max_length=250, null=True)),
                ('ayah', models.CharField(blank=True, max_length=250, null=True)),
                ('tempat_kelahiran_ayah', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_lahir_ayah', models.DateField(blank=True, null=True)),
                ('pekerjaan_ayah', models.CharField(blank=True, max_length=250, null=True)),
                ('pendidikan_ayah', models.CharField(blank=True, choices=[('Tidak Sekolah', 'Tidak Sekolah'), ('Putus SD', 'Putus SD'), ('SD Sederajat', 'SD Sederajat'), ('SMP Sederajat', 'SMP Sederajat'), ('SMA Sederajat', 'SMA Sederajat'), ('Sarjana', 'Sarjana')], max_length=200, null=True)),
                ('penghasilan_ayah', models.CharField(blank=True, choices=[('Kurang dari Rp. 1.000.000', 'Kurang dari Rp. 1.000.000'), ('Rp. 1.000.000 - Rp. 2.000.000', 'Rp. 1.000.000 - Rp. 2.000.000'), ('Lebih dari Rp. 2.000.000', 'Lebih dari Rp. 2.000.000')], max_length=200, null=True)),
                ('riwayat_ayah', models.CharField(blank=True, choices=[('Masih Hidup', 'Masih Hidup'), ('Meninggal Dunia', 'Meninggal Dunia')], max_length=200, null=True)),
                ('ibu', models.CharField(blank=True, max_length=250, null=True)),
                ('tempat_kelahiran_ibu', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_lahir_ibu', models.DateField(blank=True, null=True)),
                ('pekerjaan_ibu', models.CharField(blank=True, max_length=250, null=True)),
                ('pendidikan_ibu', models.CharField(blank=True, choices=[('Tidak Sekolah', 'Tidak Sekolah'), ('Putus SD', 'Putus SD'), ('SD Sederajat', 'SD Sederajat'), ('SMP Sederajat', 'SMP Sederajat'), ('SMA Sederajat', 'SMA Sederajat'), ('Sarjana', 'Sarjana')], max_length=200, null=True)),
                ('penghasilan_ibu', models.CharField(blank=True, choices=[('Kurang dari Rp. 1.000.000', 'Kurang dari Rp. 1.000.000'), ('Rp. 1.000.000 - Rp. 2.000.000', 'Rp. 1.000.000 - Rp. 2.000.000'), ('Lebih dari Rp. 2.000.000', 'Lebih dari Rp. 2.000.000')], max_length=200, null=True)),
                ('riwayat_ibu', models.CharField(blank=True, choices=[('Masih Hidup', 'Masih Hidup'), ('Meninggal Dunia', 'Meninggal Dunia')], max_length=200, null=True)),
                ('wali', models.CharField(blank=True, max_length=250, null=True)),
                ('tempat_kelahiran_wali', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_lahir_wali', models.DateField(blank=True, null=True)),
                ('pekerjaan_wali', models.CharField(blank=True, max_length=250, null=True)),
                ('pendidikan_wali', models.CharField(blank=True, choices=[('Tidak Sekolah', 'Tidak Sekolah'), ('Putus SD', 'Putus SD'), ('SD Sederajat', 'SD Sederajat'), ('SMP Sederajat', 'SMP Sederajat'), ('SMA Sederajat', 'SMA Sederajat'), ('Sarjana', 'Sarjana')], max_length=200, null=True)),
                ('penghasilan_wali', models.CharField(blank=True, choices=[('Kurang dari Rp. 1.000.000', 'Kurang dari Rp. 1.000.000'), ('Rp. 1.000.000 - Rp. 2.000.000', 'Rp. 1.000.000 - Rp. 2.000.000'), ('Lebih dari Rp. 2.000.000', 'Lebih dari Rp. 2.000.000')], max_length=200, null=True)),
                ('riwayat_wali', models.CharField(blank=True, choices=[('Masih Hidup', 'Masih Hidup'), ('Meninggal Dunia', 'Meninggal Dunia')], max_length=200, null=True)),
                ('agama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.agama')),
                ('bahasa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.bahasa')),
                ('kelas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.kelas')),
                ('status_anak', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.status_anak')),
                ('wilayah', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.wilayah')),
            ],
            options={
                'verbose_name_plural': 'Data Santri',
            },
        ),
        migrations.DeleteModel(
            name='Pendaftaran',
        ),
    ]
