# Generated by Django 3.2.12 on 2022-09-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0028_auto_20220918_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
