# Generated by Django 3.2.12 on 2022-09-27 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0033_auto_20220926_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='alamat_lembaga',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='alamat_sekolah',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='anak_ke',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='bahasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.bahasa'),
        ),
        migrations.AddField(
            model_name='register',
            name='berat_badan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='golongan_darah',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='kelas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.kelas'),
        ),
        migrations.AddField(
            model_name='register',
            name='keterangan_sekolah',
            field=models.CharField(blank=True, choices=[('Lulus', 'Lulus'), ('Mutasi', 'Mutasi')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='masuk_lembaga',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='nama_panggilan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='pekerjaan_wali',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='pendidikan_ayah',
            field=models.CharField(blank=True, choices=[('Tidak Sekolah', 'Tidak Sekolah'), ('Putus SD', 'Putus SD'), ('SD Sederajat', 'SD Sederajat'), ('SMP Sederajat', 'SMP Sederajat'), ('SMA Sederajat', 'SMA Sederajat'), ('Sarjana', 'Sarjana')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='pendidikan_ibu',
            field=models.CharField(blank=True, choices=[('Tidak Sekolah', 'Tidak Sekolah'), ('Putus SD', 'Putus SD'), ('SD Sederajat', 'SD Sederajat'), ('SMP Sederajat', 'SMP Sederajat'), ('SMA Sederajat', 'SMA Sederajat'), ('Sarjana', 'Sarjana')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='pendidikan_wali',
            field=models.CharField(blank=True, choices=[('Tidak Sekolah', 'Tidak Sekolah'), ('Putus SD', 'Putus SD'), ('SD Sederajat', 'SD Sederajat'), ('SMP Sederajat', 'SMP Sederajat'), ('SMA Sederajat', 'SMA Sederajat'), ('Sarjana', 'Sarjana')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='penghasilan_ayah',
            field=models.CharField(blank=True, choices=[('Kurang dari Rp. 1.000.000', 'Kurang dari Rp. 1.000.000'), ('Rp. 1.000.000 - Rp. 2.000.000', 'Rp. 1.000.000 - Rp. 2.000.000'), ('Lebih dari Rp. 2.000.000', 'Lebih dari Rp. 2.000.000')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='penghasilan_ibu',
            field=models.CharField(blank=True, choices=[('Kurang dari Rp. 1.000.000', 'Kurang dari Rp. 1.000.000'), ('Rp. 1.000.000 - Rp. 2.000.000', 'Rp. 1.000.000 - Rp. 2.000.000'), ('Lebih dari Rp. 2.000.000', 'Lebih dari Rp. 2.000.000')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='penghasilan_wali',
            field=models.CharField(blank=True, choices=[('Kurang dari Rp. 1.000.000', 'Kurang dari Rp. 1.000.000'), ('Rp. 1.000.000 - Rp. 2.000.000', 'Rp. 1.000.000 - Rp. 2.000.000'), ('Lebih dari Rp. 2.000.000', 'Lebih dari Rp. 2.000.000')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='riwayat_ayah',
            field=models.CharField(blank=True, choices=[('Masih Hidup', 'Masih Hidup'), ('Meninggal Dunia', 'Meninggal Dunia')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='riwayat_ibu',
            field=models.CharField(blank=True, choices=[('Masih Hidup', 'Masih Hidup'), ('Meninggal Dunia', 'Meninggal Dunia')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='riwayat_wali',
            field=models.CharField(blank=True, choices=[('Masih Hidup', 'Masih Hidup'), ('Meninggal Dunia', 'Meninggal Dunia')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='saudara_angkat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='saudara_kandung',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='saudara_tiri',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='status_anak',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.status_anak'),
        ),
        migrations.AddField(
            model_name='register',
            name='tempat_kelahiran_ayah',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='tempat_kelahiran_ibu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='tempat_kelahiran_wali',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='tgl_lahir_ayah',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='tgl_lahir_ibu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='tgl_lahir_wali',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='tinggi_badan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='wali',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
